name: Read Github Index and Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  read-github-index:
    name: Read GitHub Index
    runs-on: macos-latest
    outputs:
      xcode-versions: ${{ steps.read-index.outputs.xcode-versions }}
      runners: ${{ steps.read-index.outputs.runners }}
    steps:
      - name: Read GitHub Index
        id: read-index
        uses: PreternaturalAI/preternatural-github-actions/preternatural-read-github-index@aksh1t/ENG-2323
        with:
          github-index-repo: ${{ secrets.GH_INDEX_REPO }}
          github-index-read-only-pat: ${{ secrets.GH_INDEX_REPO_READ_PAT }}

  preternatural-build:
    name: Build (Xcode ${{ matrix.xcode-version }} on ${{ matrix.runner }})
    needs: read-github-index
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        xcode-version: ${{ fromJson(needs.read-github-index.outputs.xcode-versions) }}
        runner: ${{ fromJson(needs.read-github-index.outputs.runners) }}
    steps:
      - name: Run Preternatural Build
        uses: PreternaturalAI/preternatural-github-actions/preternatural-build@main
        with:
          xcode-version: ${{ matrix.xcode-version }}